# =============================================================================================== #
# _____   _              __    __   _    _   _     _   _         _____    _                       #
# / ____| | |            / _|  / _| | |  | | | |   (_) | |       |  __ \  | |                     #
# | (___   | |_    __ _  | |_  | |_  | |  | | | |_   _  | |  ___  | |__) | | |       _   _   ___  #
# \___ \  | __|  / _` | |  _| |  _| | |  | | | __| | | | | / __| |  ___/  | |      | | | | / __|  #
# ____) | | |_  | (_| | | |   | |   | |__| | | |_  | | | | \__ \ | |      | |____  |_| | | \__ \  #
# |_____/   \__|  \__,_| |_|   |_|    \____/   \__|_| |_| |___/ |_|      |______| \__,_| |___/ #
# =============================================================================================== #

# Debug mode - enables additional logging
debug-mode: false

# Database Configuration
database:
  # Whether to use a database (false = local storage only)
  enabled: false
  
  # Database type: mysql, sqlite
  type: "mysql"
  
  # MySQL Configuration (ignored for SQLite)
  host: "localhost"
  port: 3306
  name: "staffutils"
  user: "root"
  pass: "password"


vanish-fake-messages: true # When a player goes into vanish, broadcasts a fake join/leave message.


